In [1]:
import numpy as np

In [3]:
#Exercise  4

In [4]:
#1.create a null vector / 1D array of size 10 and update fifth value to 11.

In [6]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
arr=np.update(arr[5],11)

In [9]:
print(arr)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [10]:
#2.Write a NumPy program to create a 2x3 arrays and change it into 3x2 arrays

In [15]:
from numpy import*

In [21]:
a = np.array([[0, 1, 2],
              [4, 5, 6]])
print(a)

[[0 1 2]
 [4 5 6]]


In [24]:
a.shape

(2, 3)

In [22]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 4],
       [5, 6]])

In [23]:
b.shape

(3, 2)

In [25]:
#3.Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [26]:
c = np.ones((3,3))

In [27]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
c[1:-1,1:-1]=0

In [29]:
c

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [30]:
d = np.ones((6,6))
d

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
d[1:-1,1:-1]=0

In [32]:
d

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [33]:
#4.Take a look at the following matrix. Access the [2, 1,1]

In [34]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])


In [35]:
print(z)

[[[ 0  1  3]
  [ 5  7  9]
  [ 6  8 10]]

 [[ 0  2  4]
  [ 6  8 10]
  [ 0  1  3]]

 [[ 1  1  2]
  [ 5  2  9]
  [ 1  3  3]]]


In [37]:
z[2,1,1]

2